package med.voll.api;

public enum Especialidade {
    CARDIOLOGIA,
    DERMATOLOGIA,
    ENDOCRIONOLOGIA,
    GASTROENTEROLOGIA,
    GINECOLOGIA,
    NEUROLOGIA,
    OFTALMOLOGIA,
    ORTOPEDIA,
    PEDIATRIA
}
